"""Add user, session, project, and firmware file models

Revision ID: 490127e4c475
Revises: 
Create Date: 2025-10-11 10:14:52.825614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490127e4c475'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pg_trgm extension for fuzzy text search
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('tos_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('tos_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('idx_projects_deleted_at', 'projects', ['deleted_at'], unique=False)
    op.create_index('idx_projects_name_trgm', 'projects', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('idx_projects_owner_user_id', 'projects', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_user_id'), 'projects', ['owner_user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_refresh_token_hash', 'sessions', ['refresh_token_hash'], unique=False)
    op.create_index('idx_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('firmware_files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('endianness_hint', sa.String(length=10), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_firmware_files_deleted_at', 'firmware_files', ['deleted_at'], unique=False)
    op.create_index('idx_firmware_files_project_id', 'firmware_files', ['project_id'], unique=False)
    op.create_index('idx_firmware_files_sha256', 'firmware_files', ['sha256'], unique=False)
    op.create_index('idx_firmware_files_uploaded_at', 'firmware_files', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_firmware_files_project_id'), 'firmware_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_firmware_files_sha256'), 'firmware_files', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmware_files_sha256'), table_name='firmware_files')
    op.drop_index(op.f('ix_firmware_files_project_id'), table_name='firmware_files')
    op.drop_index('idx_firmware_files_uploaded_at', table_name='firmware_files')
    op.drop_index('idx_firmware_files_sha256', table_name='firmware_files')
    op.drop_index('idx_firmware_files_project_id', table_name='firmware_files')
    op.drop_index('idx_firmware_files_deleted_at', table_name='firmware_files')
    op.drop_table('firmware_files')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('idx_sessions_user_id', table_name='sessions')
    op.drop_index('idx_sessions_refresh_token_hash', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_owner_user_id'), table_name='projects')
    op.drop_index('idx_projects_owner_user_id', table_name='projects')
    op.drop_index('idx_projects_name_trgm', table_name='projects', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_projects_deleted_at', table_name='projects')
    op.drop_index('idx_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
