"""Add annotation, audit_log, and export models

Revision ID: 6ba2e143f0af
Revises: 92b67af533e6
Create Date: 2025-10-11 11:02:11.636050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ba2e143f0af'
down_revision: Union[str, Sequence[str], None] = '92b67af533e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('attestation_text', sa.String(length=1000), nullable=True),
    sa.Column('attestation_sha256', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('idx_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('idx_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_action_time', 'audit_logs', ['user_id', 'action_type', 'timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('exports',
    sa.Column('export_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attestation_sha256', sa.String(length=64), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('json', 'pdf', 'csv')", name='ck_exports_format'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_id')
    )
    op.create_index('idx_exports_created_at', 'exports', ['created_at'], unique=False)
    op.create_index('idx_exports_expires_at', 'exports', ['expires_at'], unique=False)
    op.create_index('idx_exports_project_id', 'exports', ['project_id'], unique=False)
    op.create_index('idx_exports_user_id', 'exports', ['user_id'], unique=False)
    op.create_index(op.f('ix_exports_expires_at'), 'exports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_index(op.f('ix_exports_user_id'), 'exports', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('annotation_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("validation_status IS NULL OR validation_status IN ('verified', 'rejected', 'uncertain')", name='ck_annotations_validation_status'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_id')
    )
    op.create_index('idx_annotations_candidate_id', 'annotations', ['candidate_id'], unique=False)
    op.create_index('idx_annotations_created_at', 'annotations', ['created_at'], unique=False)
    op.create_index('idx_annotations_tags', 'annotations', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_annotations_user_id', 'annotations', ['user_id'], unique=False)
    op.create_index(op.f('ix_annotations_candidate_id'), 'annotations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_candidate_id'), table_name='annotations')
    op.drop_index('idx_annotations_user_id', table_name='annotations')
    op.drop_index('idx_annotations_tags', table_name='annotations', postgresql_using='gin')
    op.drop_index('idx_annotations_created_at', table_name='annotations')
    op.drop_index('idx_annotations_candidate_id', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_exports_user_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_expires_at'), table_name='exports')
    op.drop_index('idx_exports_user_id', table_name='exports')
    op.drop_index('idx_exports_project_id', table_name='exports')
    op.drop_index('idx_exports_expires_at', table_name='exports')
    op.drop_index('idx_exports_created_at', table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_action_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_type', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
