"""Add scan_job and candidate models

Revision ID: 92b67af533e6
Revises: 490127e4c475
Create Date: 2025-10-11 10:43:32.706311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b67af533e6'
down_revision: Union[str, Sequence[str], None] = '490127e4c475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_jobs',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scan_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed')", name='ck_scan_jobs_status'),
    sa.ForeignKeyConstraint(['file_id'], ['firmware_files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_index('idx_scan_jobs_created_at', 'scan_jobs', ['created_at'], unique=False)
    op.create_index('idx_scan_jobs_file_id', 'scan_jobs', ['file_id'], unique=False)
    op.create_index('idx_scan_jobs_status', 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_file_id'), 'scan_jobs', ['file_id'], unique=False)
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_table('candidates',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('byte_offset_start', sa.BigInteger(), nullable=False),
    sa.Column('byte_offset_end', sa.BigInteger(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detection_method_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('1D', '2D', '3D', 'scalar')", name='ck_candidates_type'),
    sa.CheckConstraint('byte_offset_end > byte_offset_start', name='ck_candidates_byte_offset_order'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_candidates_confidence_range'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_jobs.scan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('idx_candidates_byte_offset_end', 'candidates', ['byte_offset_end'], unique=False)
    op.create_index('idx_candidates_byte_offset_start', 'candidates', ['byte_offset_start'], unique=False)
    op.create_index('idx_candidates_confidence', 'candidates', ['confidence'], unique=False)
    op.create_index('idx_candidates_scan_id', 'candidates', ['scan_id'], unique=False)
    op.create_index('idx_candidates_type', 'candidates', ['type'], unique=False)
    op.create_index(op.f('ix_candidates_byte_offset_end'), 'candidates', ['byte_offset_end'], unique=False)
    op.create_index(op.f('ix_candidates_byte_offset_start'), 'candidates', ['byte_offset_start'], unique=False)
    op.create_index(op.f('ix_candidates_confidence'), 'candidates', ['confidence'], unique=False)
    op.create_index(op.f('ix_candidates_scan_id'), 'candidates', ['scan_id'], unique=False)
    op.create_index(op.f('ix_candidates_type'), 'candidates', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_type'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_scan_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_confidence'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_byte_offset_start'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_byte_offset_end'), table_name='candidates')
    op.drop_index('idx_candidates_type', table_name='candidates')
    op.drop_index('idx_candidates_scan_id', table_name='candidates')
    op.drop_index('idx_candidates_confidence', table_name='candidates')
    op.drop_index('idx_candidates_byte_offset_start', table_name='candidates')
    op.drop_index('idx_candidates_byte_offset_end', table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_file_id'), table_name='scan_jobs')
    op.drop_index('idx_scan_jobs_status', table_name='scan_jobs')
    op.drop_index('idx_scan_jobs_file_id', table_name='scan_jobs')
    op.drop_index('idx_scan_jobs_created_at', table_name='scan_jobs')
    op.drop_table('scan_jobs')
    # ### end Alembic commands ###
